cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import path

from . import views
from .views import marks_filter

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<id>/<slug>/', views.product_detail, name='product_detail'),
    path('submit_review/', views.submit_review, name='submit_review'),
    path('marks_filter/', marks_filter, name='marks_filter'),

]

myShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('catalog/', include('catalog.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('promocodes/', include('promocode.urls')),
    path('payment/', include('payment.urls')),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Type(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Type'
        verbose_name_plural = 'Types'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_type',
                       args=[self.slug])


class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_brand',
                       args=[self.slug])


class Backlight(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Backlight'
        verbose_name_plural = 'Backlights'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_backlight',
                       args=[self.slug])


class Product(models.Model):
    type = models.ForeignKey(Type, related_name='products', default='0000000',
                             on_delete=models.CASCADE, )
    brand = models.ForeignKey(Brand, related_name='brands', default='0000000',
                              on_delete=models.CASCADE, )
    backlight = models.ForeignKey(Backlight, related_name='lights', default='0000000',
                                 on_delete=models.CASCADE, )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail',
                       args=[self.id, self.slug])


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"Review for {self.product} by {self.user}"
    def get_review_author(self):
        return self.user

catalog/forms.py
# forms.py
from django import forms
from .models import Review

class ReviewForm(forms.Form):
    review_text = forms.CharField(widget=forms.Textarea)
    product_id = forms.IntegerField(widget=forms.HiddenInput)

catalog/views.py
from cart.forms import CartAddProductForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .filters import ProductFilter
from .models import Product, Type, Review, Backlight, Brand
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .forms import ReviewForm


def marks_filter(request):
    type_slug = request.GET.get('type_slug')
    backlight = request.GET.get('backlight')
    brand = request.GET.get('brand')
    o = request.GET.get('o')
    marks = []

    if type_slug:
        type = get_object_or_404(Type, slug=type_slug)
        products = Product.objects.filter(type=type, backlight=backlight, brand=brand, o=o)
        marks = list(products.values_list('mark', flat=True).distinct())

    return JsonResponse({'marks': marks}, safe=False)

def product_list(request, type_slug=None):
    type = None
    types = Type.objects.all()
    products = Product.objects.filter(available=True)
    if type_slug:
        type = get_object_or_404(Type, slug=type_slug)
        products = products.filter(type=type)

    f = ProductFilter(request.GET, queryset=Product.objects.all())
    has_filter = any(field in request.GET for field in set(f.get_fields()))

    context = {
        'type': type,
        'types': types,
        'products': products,
        'filter': f,
        'has_filter': has_filter
    }

    return render(request,
                  'catalog/product/list.html',
                  context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }

    return render(request, 'catalog/product/detail.html', context)


def submit_review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            product_id = form.cleaned_data['product_id']
            text = form.cleaned_data['review_text']

            # Получаем продукт и текущего пользователя
            product = Product.objects.get(id=product_id)
            user = request.user

            # Создаем и сохраняем отзыв
            review = Review.objects.create(product=product, user=user, text=text)

            # Дополнительные действия, если необходимо
            messages.success(request, 'Отзыв успешно добавлен.')
            # Очистка формы
    else:
        messages.error(request, 'Ошибка при добавлении отзыва.')
    return redirect('cart_detail')

templates/catalog/product/detail.html
{% extends 'main.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    {{ product.name }}
{% endblock title %}
<head>
    <meta name="keywords" content="компьютер, видеокарта, диск, клавиатура, мышь, виндус">
</head>
{% block content %}
    <div class="row mb-5">
        <div class="col-md-4 position-relative m-auto mb-4">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/logo.png' %}{% endif %}" class="img-thumbnail img-rounded mb-3">

            {% if user.is_authenticated %}
                <form action="{% url 'cart_add' product.id %}" method="post" class="d-flex justify-content-between">
                    <div class="w-100 me-3">
                        {{ cart_product_form }}
                        {% csrf_token %}
                    </div>
                    <input type="submit" value="Купить" class="btn btn-success w-100">
                </form>
            {% else %}
                <button type="button" class="btn w-100 btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Купить
                </button>
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header border-0">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body px-2 py-3 text-center">
                                Для покупки {{ product.name }} необходимо авторизоваться
                            </div>
                            <div class="modal-footer border-0 d-flex justify-content-between">
                                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Отмена</button>
                                <a href="{% url 'login' %}">
                                    <button type="button" class="btn btn-danger">Войти</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="col-md-8">
            <h3 class="mb-5">{{ product.name }}</h3>
            <div class="d-flex justify-content-between mb-2">
                <div class="me-3">Цена</div>
                <div class="text-truncate fw-semibold">
                    {{ product.price }} руб
                </div>
            </div>
            <!-- Добавьте остальные блоки информации о товаре здесь -->
            <div class="d-flex justify-content-between mb-2">
                <div class="me-3">Тип комплектующего</div>
                <div class="text-truncate">
                    {{ product.type }}
                </div>
            </div>
            <div class="d-flex justify-content-between mb-2">
                <div class="me-3">Производитель</div>
                <div class="text-truncate">
                    {{ product.brand }}
                </div>
            </div>
            <div class="d-flex justify-content-between mb-2">
                <div class="me-3">Тип подсветки</div>
                <div class="text-truncate">
                    {{ product.backlight }}
                </div>
            </div>
            <div class="">
                <div class="me-3">Описание</div>
                <div class="text-truncate">
                    {{ product.description }}
                </div>
            </div>
            <!-- Отображение отзывов внизу -->
            <h4 class="mt-4 mb-3">Отзывы</h4>
            {% if product.reviews.count > 0 %}
                {% for review in product.reviews.all %}
                    <div class="mb-2">
                        <strong>{{ review.get_review_author }}</strong>: {{ review.text }}
                    </div>
                {% endfor %}
            {% else %}
                <p>На этот товар еще никто не оставил отзыв.</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/catalog/product/detail_old.html
{% extends 'main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    {{ product.name }}
{% endblock title %}
{% block content %}
    <div class="row mb-5">
        <div class="col-4 position-relative m-auto">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/logo.png' %}{% endif %}"
        class="img-thumbnail img-rounded mb-3">
            {% if user.is_authenticated %}
                    <form action="{% url 'cart_add' product.id %}" method="post" class="d-flex justify-content-between">
                        <div class="w-100 me-3">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        </div>
                        <input type="submit" value="Купить" class="btn btn-success w-100">
                    </form>
                    {% else %}
                    <button type="button" class="btn w-100 btn-success"
                            data-bs-toggle="modal" data-bs-target="#exampleModal">
                        купить
                    </button>
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header border-0">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body px-2 py-3 text-center">
                                    Для покупки {{ product.name }} необходимо авторизоваться
                                </div>
                                <div class="modal-footer border-0 d-flex justify-content-between">
                                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Отмена</button>
                                    <a href="{% url 'login' %}">
                                        <button type="button" class="btn btn-danger">Войти</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
        </div>
        <div class="col ms-4">
                    <h3 class="mb-5">{{ product.name }}</h3>
                    <div class="d-flex justify-content-between mb-2">
                        <div class="me-3">Цена</div>
                        <div class="text-truncate fw-semibold">
                            {{ product.price }} руб
                        </div>
                    </div>
                    <div class="d-flex justify-content-between mb-2">
                        <div class="me-3">Тип комплектующего</div>
                        <div class="text-truncate">
                            {{ product.type }}
                        </div>
                    </div>
                    <div class="d-flex justify-content-between mb-2">
                        <div class="me-3">Производитель</div>
                        <div class="text-truncate">
                            {{ product.brand }}
                        </div>
                    </div>
                    <div class="d-flex justify-content-between mb-2">
                        <div class="me-3">Тип подсветки</div>
                        <div class="text-truncate">
                            {{ product.backlight }}
                        </div>
                    </div>
                    <div class="">
                        <div class="me-3">Описание</div>
                        <div class="text-truncate">
                             {{ product.description }}
                        </div>
                    </div>
            </div>
    </div>
{% endblock content %}

templates/catalog/product/list.html
{% extends 'main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Каталог
{% endblock title %}
{% block content %}
<h1 class="mb-4">Каталог</h1>
<form method="get" class="text-lowercase text-center mb-3 d-flex">
    {% render_field filter.form.s class="form-control" %}
    <button type="submit" class="btn pt-1 pb-2 ms-2 btn-outline-secondary">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg>
    </button>
</form>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_type').change(function() {
            var type_slug = $(this).val();
            var backlight = $('#id_backlight').val();
            var brand = $('#id_brand').val();
            var o = $('#id_o').val();

            $.ajax({
                url: '{% url "marks_filter" %}',
                data: {'type_slug': type_slug, 'backlight': backlight, 'brand': brand, 'o': o},
                dataType: 'json',
                success: function(data) {
                    var options = '<option value="">Все марки</option>';
                    for (var i = 0; i < data.marks.length; i++) {
                        options += '<option value="' + data.marks[i] + '">' + data.marks[i] + '</option>';
                    }
                    $('#id_mark').html(options);
                }
            });
        });
    });
</script>
<div class="d-flex justify-content-between align-items-end mb-5">
    <form method="get" class="d-flex justify-content-between w-100 me-2">
             <div class="col-2">
                 <div class="fw-semibold">Тип комплектующего</div>
                {% render_field filter.form.type class="form-control" %}
             </div>
             <div class="col-2">
                 <div class="fw-semibold">Тип подсветки</div>
                {% render_field filter.form.backlight class="form-control" %}
             </div>
             <div class="col-2">
                 <div class="fw-semibold">Производитель</div>
                {% render_field filter.form.brand class="form-control" %}
             </div>
             <div class="col-2">
                 <div class="fw-semibold">Цена</div>
                {% render_field filter.form.o class="form-control" %}
             </div>
            <div class="mt-auto">
                <button type="submit" class="btn btn-success ms-2">Применить</button>
            </div>
     </form>
    <a href="{%  url 'product_list' %}">
        <button class="btn btn-outline-secondary">Сбросить</button>
    </a>
</div>
        <div class="row row-cols-2 row-cols-md-4 g-3">
            {% if filter.qs %}
            {% for product in filter.qs %}
            <div class="col">
                <div class="card">
                    <a href="{{ product.get_absolute_url }}"
                       class="text-decoration-none text-black">
                        <img src="{% if product.image %}
                                    {{ product.image.url }}
                                    {% else %}
                                    {% static 'img/logo.png' %}
                                    {% endif %}"
                             class="card-img-top">
                        <div class="card-body text-center border-top">
                            <div class="card-title text-truncate">{{ product.name }}</div>
                            <h5 class="card-text">{{ product.price }} руб</h5>
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
            {% else %}
                <p style="width: 100%; text-align: center">По вашему запросу результатов не найдено! Попробуйте изменить условия поиска</p>
            {% endif %}
        </div>
{% endblock content %}