cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

myShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('catalog/', include('catalog.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('promocodes/', include('promocode.urls')),
    path('payment/', include('payment.urls')),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
 path('process/', views.payment_process, name='process'),
 path('completed/', views.payment_completed, name='completed'),
 path('canceled/', views.payment_canceled, name='canceled'),
 path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),

]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse, get_object_or_404
from orders.models import Order

# создать экземпляр Stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(
        reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(
        reverse('payment:canceled'))
        # данные сеанса Stripe оформления платежа
        session_data = {
        'mode': 'payment',
        'success_url': success_url,
        'cancel_url': cancel_url,
        'line_items': []
        }
        # добавить товарные позиции заказа
        # в сеанс оформления платежа Stripe
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'rub',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                    'quantity': item.quantity,
                })
        # создать сеанс оформления платежа Stripe
        session = stripe.checkout.Session.create(**session_data)
        # перенаправит к платежной форме Stripe
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())

def payment_completed(request):
    return render(request, 'payment/completed.html')

def payment_canceled(request):
    return render(request, 'payment/canceled.html')

templates/payment/canceled.html
{% extends "main.html" %}
{% block title %}Не оплачено{% endblock %}
{% block content %}
    <h1>Оплата не была завершена</h1>
{% endblock %}

templates/payment/completed.html
{% extends "main.html" %}

{% block title %}Оплачено{% endblock %}

{% block content %}
    <h1>Заказ был успешно оплачен</h1>
    <p>Ожидайте звонка оператора для уточнения деталей доставки!</p>
{% endblock %}

templates/payment/process.html
{% extends "main.html" %}
{% load static %}
{% block title %}Pay your order{% endblock %}
{% block content %}
    <h1>Оплата</h1>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Товар</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Кол-во</th>
                    <th scope="col">Итого</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.items.all %}
                    <tr class="{% cycle 'table-light' 'table-info' %}">
                        <td>{{ item.product.name }}</td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">{{ item.quantity }}</td>
                        <td class="num">${{ item.get_cost }}</td>
                    </tr>
                {% endfor %}
                <tr class="table-primary">
                    <td colspan="3">К оплате:</td>
                    <td class="num">${{ order.get_total_cost }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <form action="{% url 'payment:process' %}" method="post">
        <button type="submit" class="btn btn-success">Оплатить</button>
        {% csrf_token %}
    </form>
{% endblock %}